//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CSubset.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICSubsetListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class CSubsetBaseListener : ICSubsetListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstrucciones([NotNull] CSubsetParser.InstruccionesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstrucciones([NotNull] CSubsetParser.InstruccionesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.instruccion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruccion([NotNull] CSubsetParser.InstruccionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.instruccion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruccion([NotNull] CSubsetParser.InstruccionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.decision"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecision([NotNull] CSubsetParser.DecisionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.decision"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecision([NotNull] CSubsetParser.DecisionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSentencia([NotNull] CSubsetParser.SentenciaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.sentencia"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSentencia([NotNull] CSubsetParser.SentenciaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.salida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSalida([NotNull] CSubsetParser.SalidaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.salida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSalida([NotNull] CSubsetParser.SalidaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.terminar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminar([NotNull] CSubsetParser.TerminarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.terminar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminar([NotNull] CSubsetParser.TerminarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.condicion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondicion([NotNull] CSubsetParser.CondicionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.condicion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondicion([NotNull] CSubsetParser.CondicionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.cadena"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCadena([NotNull] CSubsetParser.CadenaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.cadena"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCadena([NotNull] CSubsetParser.CadenaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.caracteres"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaracteres([NotNull] CSubsetParser.CaracteresContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.caracteres"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaracteres([NotNull] CSubsetParser.CaracteresContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.caracter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaracter([NotNull] CSubsetParser.CaracterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.caracter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaracter([NotNull] CSubsetParser.CaracterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.simbolo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimbolo([NotNull] CSubsetParser.SimboloContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.simbolo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimbolo([NotNull] CSubsetParser.SimboloContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
